server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: ${MYSQL_URL:jdbc:h2:mem:buffetease}
    username: ${MYSQL_USER:sa}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: ${MYSQL_DRIVER:org.h2.Driver}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.hibernate.SQL: debug

